In [1]:
import pandas as pd

In [2]:
box_scores = pd.read_csv("nbascoresdata.csv", index_col=0)
box_scores

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240,39,81,0.481,6,20,0.300,14,18,0.778,...,22.8,29.0,178,111,DAL,95,1,2016,12/9/2015,True
1,240,36,100,0.360,7,31,0.226,16,19,0.842,...,50.0,32.6,152,111,ATL,98,0,2016,12/9/2015,False
2,240,37,85,0.435,8,19,0.421,17,23,0.739,...,20.0,30.9,148,116,SAS,107,1,2018,10/18/2017,False
3,240,41,89,0.461,8,21,0.381,17,19,0.895,...,28.6,30.9,138,118,MIN,99,0,2018,10/18/2017,True
4,240,27,86,0.314,6,26,0.231,15,20,0.750,...,16.8,30.9,157,90,MEM,92,1,2021,4/30/2021,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240,35,81,0.432,11,26,0.423,27,36,0.750,...,34.2,33.7,160,118,OKC,92,0,2019,10/19/2018,True
17768,240,37,74,0.500,13,25,0.520,26,37,0.703,...,25.0,30.0,139,129,ORL,108,1,2017,12/14/2016,True
17769,240,42,89,0.472,14,33,0.424,10,20,0.500,...,25.6,29.9,175,126,LAC,113,0,2017,12/14/2016,False
17770,240,41,85,0.482,9,26,0.346,26,30,0.867,...,27.7,27.1,150,126,MIA,106,1,2020,9/19/2020,True
17771,240,33,85,0.388,12,44,0.273,28,34,0.824,...,51.5,36.2,141,114,BOS,117,0,2020,9/19/2020,False

In [3]:
box_scores = box_scores.sort_values("date")

In [4]:
box_scores = box_scores.reset_index(drop=True)

In [5]:
def nextGame(group):
    group["next_game"] = group["won"].shift(-1)
    return group

box_scores = box_scores.groupby("team", group_keys=False).apply(nextGame)

In [6]:
box_scores["next_game"][pd.isnull(box_scores["next_game"])] = 2
box_scores["next_game"] = box_scores["next_game"].astype(int, errors="ignore")

C:\Users\15169\AppData\Local\Temp\ipykernel_2400\1230976220.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  box_scores["next_game"][pd.isnull(box_scores["next_game"])] = 2

In [7]:
nulls = pd.isnull(box_scores).sum()
nulls = nulls[nulls > 0]
valid_columns = box_scores.columns[~box_scores.columns.isin(nulls.index)]
box_scores = box_scores[valid_columns].copy()

In [8]:
box_scores

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,next_game
0,240,36,91,0.396,15,33,0.455,17,18,0.944,...,30.6,174,130,CHO,94,0,2016,1/1/2016,True,1
1,240,33,87,0.379,5,16,0.313,22,29,0.759,...,40.4,150,105,PHI,84,0,2016,1/1/2016,True,0
2,240,39,85,0.459,10,16,0.625,20,25,0.800,...,39.6,171,132,NYK,81,0,2016,1/1/2016,True,0
3,240,31,84,0.369,6,19,0.316,13,17,0.765,...,42.7,195,102,CHI,108,1,2016,1/1/2016,False,0
4,240,31,84,0.369,4,24,0.167,18,25,0.720,...,30.6,164,100,LAL,93,1,2016,1/1/2016,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240,38,81,0.469,12,30,0.400,14,14,1.000,...,37.2,151,123,LAL,112,0,2020,9/8/2020,False,2
17768,240,27,68,0.397,9,27,0.333,22,26,0.846,...,34.3,143,106,LAC,96,0,2020,9/9/2020,False,2
17769,240,33,79,0.418,8,28,0.286,22,30,0.733,...,35.5,162,117,DEN,85,1,2020,9/9/2020,True,2
17770,290,44,101,0.436,19,47,0.404,18,25,0.720,...,32.5,300,120,BOS,122,1,2020,9/9/2020,True,2
17771,290,44,100,0.440,19,46,0.413,15,18,0.833,...,23.7,149,117,TOR,125,0,2020,9/9/2020,False,2

In [9]:
from sklearn.linear_model import RidgeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.model_selection import TimeSeriesSplit

rr = RidgeClassifier(alpha=1)

split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split, n_jobs=1)

In [10]:
removed_columns = ["season", "date", "won", "next_game", "team", "team_opp"]
selected_columns = box_scores.columns[~box_scores.columns.isin(removed_columns)]

In [11]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
box_scores[selected_columns] = scaler.fit_transform(box_scores[selected_columns])

In [12]:
box_scores

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,next_game
0,0.0,0.386364,0.455882,0.303828,0.517241,0.439394,0.540380,0.372093,0.269841,0.934656,...,0.109114,0.402844,0.623529,CHO,0.288462,0.0,2016,1/1/2016,True,1
1,0.0,0.318182,0.397059,0.263158,0.172414,0.181818,0.371734,0.488372,0.444444,0.718786,...,0.234917,0.289100,0.329412,PHI,0.192308,0.0,2016,1/1/2016,True,0
2,0.0,0.454545,0.367647,0.454545,0.344828,0.181818,0.742280,0.441860,0.380952,0.766628,...,0.224647,0.388626,0.647059,NYK,0.163462,0.0,2016,1/1/2016,True,0
3,0.0,0.272727,0.352941,0.239234,0.206897,0.227273,0.375297,0.279070,0.253968,0.725788,...,0.264442,0.502370,0.294118,CHI,0.423077,1.0,2016,1/1/2016,False,0
4,0.0,0.272727,0.352941,0.239234,0.137931,0.303030,0.198337,0.395349,0.380952,0.673279,...,0.109114,0.355450,0.270588,LAL,0.278846,1.0,2016,1/1/2016,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.431818,0.308824,0.478469,0.413793,0.393939,0.475059,0.302326,0.206349,1.000000,...,0.193838,0.293839,0.541176,LAL,0.461538,0.0,2020,9/8/2020,False,2
17768,0.0,0.181818,0.117647,0.306220,0.310345,0.348485,0.395487,0.488372,0.396825,0.820303,...,0.156611,0.255924,0.341176,LAC,0.307692,0.0,2020,9/9/2020,False,2
17769,0.0,0.318182,0.279412,0.356459,0.275862,0.363636,0.339667,0.488372,0.460317,0.688448,...,0.172015,0.345972,0.470588,DEN,0.201923,1.0,2020,9/9/2020,True,2
17770,0.5,0.568182,0.602941,0.399522,0.655172,0.651515,0.479810,0.395349,0.380952,0.673279,...,0.133504,1.000000,0.505882,BOS,0.557692,1.0,2020,9/9/2020,True,2
17771,0.5,0.568182,0.588235,0.409091,0.655172,0.636364,0.490499,0.325581,0.269841,0.805134,...,0.020539,0.284360,0.470588,TOR,0.586538,0.0,2020,9/9/2020,False,2

In [13]:
sfs.fit(box_scores[selected_columns], box_scores["next_game"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30, n_jobs=1)

In [14]:
predictors = list(selected_columns[sfs.get_support()])

In [15]:
predictors

['mp',
 'fga',
 'efg%',
 'ast%',
 'usg%',
 'fg_max',
 'fga_max',
 '3pa_max',
 'ft%_max',
 'orb_max',
 'drb_max',
 'ftr_max',
 'orb%_max',
 'drb%_max',
 'mp_opp',
 'fga_opp',
 'trb_opp',
 'stl_opp',
 'pf_opp',
 'ast%_opp',
 'blk%_opp',
 'usg%_opp',
 '3p_max_opp',
 '3p%_max_opp',
 'ft%_max_opp',
 'ast_max_opp',
 'trb%_max_opp',
 'blk%_max_opp',
 'tov%_max_opp',
 'ortg_max_opp']

In [18]:
def backtest(scores, datamodel, predictors, start=3, step=1):
    all_predictions = []
    
    seasons = sorted(scores["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = scores[scores["season"] < season]
        test = scores[scores["season"] == season]
        
        datamodel.fit(train[predictors], train["next_game"])
        
        preds = datamodel.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["next_game"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [19]:
predictions = backtest(box_scores, rr, predictors)

from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"], predictions["prediction"])

0.5079814103859366

In [20]:
predictions

       actual  prediction
28          0           1
29          0           0
30          1           1
31          1           1
32          1           1
...       ...         ...
17353       0           1
17392       1           1
17393       1           1
17416       0           1
17417       0           1

[9898 rows x 2 columns]